apiVersion: v2
name: ska-low-aavs3
description: A Helm chart for AAVS3
type: application
version: 0.0.1
appVersion: 0.0.1
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:

# Signal chain
- name: ska-low-mccs-spshw
  version: 0.4.0
  repository: https://artefact.skao.int/repository/helm-internal
# - name: ska-low-mccs-daq
#   version: 0.2.0
#   repository: file://../ska-low-mccs-daq

# # Jupyterhub
# - name: jupyterhub
#   version: 2.0.0
#   repository: https://jupyterhub.github.io/helm-chart/

# # Taranta
# - name: ska-tango-taranta
#   version: 1.3.8
#   repository: https://artefact.skao.int/repository/helm-internal
#   condition: ska-taranta.enabled
# - name: ska-tango-tangogql
#   version: 1.3.6
#   repository: https://artefact.skao.int/repository/helm-internal
#   condition: ska-taranta.enabled
# # - name: ska-taranta-auth
# #   version: 0.1.5
# #   repository: https://artefact.skao.int/repository/helm-internal
# #   condition: ska-taranta-auth.enabled
# # - name: ska-tango-taranta-dashboard
# #   version: 1.3.0
# #   repository: https://artefact.skao.int/repository/helm-internal
# #   condition: ska-taranta-dashboard.enabled
# # - name: ska-tango-taranta-dashboard-pvc
# #   version: 1.3.0
# #   repository: https://artefact.skao.int/repository/helm-internal
# #   condition: ska-taranta-dashboard.enabled

# base
- name: ska-tango-util
  version: 0.4.1
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-base
  version: 0.3.23
  repository: https://artefact.skao.int/repository/helm-internal
