global:
  minikube: false
  tango_host: tango-databaseds:10000
  facility: aavs3
  annotations: ~
  sub-system:
    ska-tango-base:
      enabled: false
    taranta:
      enabled: false
    archiver:
      enabled: false

ska-low-mccs-spshw:
  ska-tango-base:
    enabled: false
  facility:
    subracks:
      instances:
        1:
          host: 10.134.0.1  # TODO: fictional IP address.
          port: 8081
        2:
          host: 10.134.0.2  # TODO: fictional IP address.
          port: 8081
    tpms:
      version: tpm_v1_6
      port: 10000
      instances:
        1:
          host: 10.134.1.1  # TODO: fictional IP address.
          subrack: "1"
          subrack_bay: 1
        2:
          host: 10.134.1.2  # TODO: fictional IP address.
          subrack: "1"
          subrack_bay: 2
        3:
          host: 10.134.1.3  # TODO: fictional IP address.
          subrack: "1"
          subrack_bay: 3
        4:
          host: 10.134.1.4  # TODO: fictional IP address.
          subrack: "1"
          subrack_bay: 4
        5:
          host: 10.134.1.5  # TODO: fictional IP address.
          subrack: "1"
          subrack_bay: 5
        6:
          host: 10.134.1.6  # TODO: fictional IP address.
          subrack: "1"
          subrack_bay: 6
        7:
          host: 10.134.1.7  # TODO: fictional IP address.
          subrack: "1"
          subrack_bay: 7
        8:
          host: 10.134.1.8  # TODO: fictional IP address.
          subrack: "1"
          subrack_bay: 8
        9:
          host: 10.134.2.1  # TODO: fictional IP address.
          subrack: "2"
          subrack_bay: 1
        10:
          host: 10.134.2.2  # TODO: fictional IP address.
          subrack: "2"
          subrack_bay: 2
        11:
          host: 10.134.2.3  # TODO: fictional IP address.
          subrack: "2"
          subrack_bay: 3
        12:
          host: 10.134.2.4  # TODO: fictional IP address.
          subrack: "2"
          subrack_bay: 4
        13:
          host: 10.134.2.5  # TODO: fictional IP address.
          subrack: "2"
          subrack_bay: 5
        14:
          host: 10.134.2.6  # TODO: fictional IP address.
          subrack: "2"
          subrack_bay: 6
        15:
          host: 10.134.2.7  # TODO: fictional IP address.
          subrack: "2"
          subrack_bay: 7
        16:
          host: 10.134.2.8  # TODO: fictional IP address.
          subrack: "2"
          subrack_bay: 8
  simulators:
    subracks:
      1:
        host: subrack-simulator-1
      2:
        host: subrack-simulator-2
  deviceServers:
    subracks:
      logging_level_default: 5
    tpms:
      logging_level_default: 5
      simulation_config: 1
      test_config: 1

# ska-low-mccs-daq:
#   ska-tango-base:
#     enabled: false
#   low_mccs_daq:
#     enabled: true
#     image:
#       registry: artefact.skao.int
#       image: ska-low-mccs-daq
#       tag: 0.2.0
#       pullPolicy: IfNotPresent
#   securityContext:
#     capabilities:
#       add: ["NET_RAW", "IPC_LOCK", "SYS_NICE", "SYS_ADMIN", "KILL", "SYS_TIME"]
#   deviceServers:
#     daqreceiver:
#       file: "data/daq-receiver.yaml"
#       devices:
#         - name: daqreceiver-001
#           device_name: low-mccs/daqreceiver/001  # mandatory
#           daq_id: 1  # optional: defaults to position in this list
#           receiver_interface: enp216s0f0  # optional: defaults to "eth0"
#           receiver_ip: ""  # mandatory
#           receiver_port: 4660  # optional: defaults to 4660
#           grpc_port: 50051
#           grpc_ip: "10.128.16.50" 
