apiVersion: apps/v1
kind: Deployment
metadata:
  name: aavs3-landing
  labels:
    app: aavs3-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aavs3-landing
  template:
    metadata:
      labels:
        app: aavs3-landing
    spec:
      containers:
      - name: aavs3-landing
        image: {{$.Values.image.registry}}/{{$.Values.image.name}}:{{$.Values.image.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
