apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: aavs3-landing-service
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: aavs3-landing-service
            port:
              number: 80
        path: /
        pathType: Prefix
