apiVersion: v1
kind: Service
metadata:
  name: aavs3-landing-service
spec:
  selector:
    app: aavs3-landing
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
